1. Read mobile dataset using pandas, and preprocess it (fill null values).

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
from google.colab import files 
uploaded = files.upload()

Saving mobile_cleaned-1549119762886.csv to mobile_cleaned-1549119762886.csv


In [ ]:
data=pd.read_csv('mobile_cleaned-1549119762886.csv')
print(data)

     sim_type  aperture  gpu_rank  ...  battery_capacity  processor_rank  is_liked
0           0        12        55  ...              2000             125         1
1           0         1        55  ...              2000             165         1
2           0         9        55  ...              2500             164         0
3           0         8        55  ...              3000             165         1
4           1         1        55  ...              3000             165         0
..        ...       ...       ...  ...               ...             ...       ...
104         3        10        14  ...              3410               8         1
105         0         5         3  ...              3600             101         1
106         3        10         6  ...              2750               1         1
107         3        10        12  ...              1810               7         1
108         2         8         3  ...              3000               2         0

[10

In [ ]:
data.isnull().sum()

sim_type                             0
aperture                             0
gpu_rank                             0
weight                               1
stand_by_time                        3
processor_frequency                  0
thickness                            0
flash_type                           0
front_camera_resolution              0
auto_focus                           0
screen_size                          0
frames_per_second                    0
FM                                   0
no_of_reviews_in_gsmarena_in_week    2
os                                   0
phone_height                         1
screen_protection                    0
sim_size                             0
price                                0
talk_time                            1
video_resolution                     1
display_resolution                   0
removable_battery                    0
display_type                         0
primary_camera_resolution            1
battery_type             

In [ ]:
data.isnull().sum().sum()


10

In [ ]:
data.describe()

sim_type    aperture  ...  processor_rank    is_liked
count  109.000000  109.000000  ...      109.000000  109.000000
mean     0.981651    7.733945  ...       50.788991    0.844037
std      1.347025    3.201973  ...       49.496366    0.364496
min      0.000000    0.000000  ...        1.000000    0.000000
25%      0.000000    8.000000  ...       12.000000    1.000000
50%      0.000000    8.000000  ...       21.000000    1.000000
75%      3.000000   10.000000  ...       92.000000    1.000000
max      4.000000   14.000000  ...      166.000000    1.000000

[8 rows x 40 columns]

In [ ]:
data['weight']=data['weight'].fillna(data['weight'].mean())
data['stand_by_time']=data['stand_by_time'].fillna(data['stand_by_time'].mean())
data['no_of_reviews_in_gsmarena_in_week']=data['no_of_reviews_in_gsmarena_in_week'].fillna(data['no_of_reviews_in_gsmarena_in_week'].mean())
data['phone_height']=data['phone_height'].fillna(data['phone_height'].mean())
data['talk_time']=data['talk_time'].fillna(data['talk_time'].mean())
data['video_resolution']=data['video_resolution'].fillna(data['video_resolution'].mean())
data['primary_camera_resolution']=data['primary_camera_resolution'].fillna(data['primary_camera_resolution'].mean())

In [ ]:
data.isnull().sum()

sim_type                             0
aperture                             0
gpu_rank                             0
weight                               0
stand_by_time                        0
processor_frequency                  0
thickness                            0
flash_type                           0
front_camera_resolution              0
auto_focus                           0
screen_size                          0
frames_per_second                    0
FM                                   0
no_of_reviews_in_gsmarena_in_week    0
os                                   0
phone_height                         0
screen_protection                    0
sim_size                             0
price                                0
talk_time                            0
video_resolution                     0
display_resolution                   0
removable_battery                    0
display_type                         0
primary_camera_resolution            0
battery_type             

In [ ]:
data.isnull().sum().sum()

0

3. Compute outer product of 2 vectors.
Eg:
 
original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [ ]:
import numpy as np
p=[[1, 0], [0, 1]]
q=[[1, 2], [3, 4]]
np.outer(p,q)

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

4. Write a NumPy program to compute the condition number of a given matrix.


In [ ]:
import numpy as np
import numpy.linalg as nl
array2=np.array([[1,2],[3,4]])
x=nl.cond(array2)
x

14.933034373659268

5. write a NumPy program to compute the sum of the diagonal element of a given array(matrix).

In [ ]:
import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.trace(array1)

15